# Generated by Django 4.2.30 on 2026-09-05 18:49

import apps.course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('file', models.FileField(upload_to=apps.course.models.material_upload_path)),
                ('filename', models.CharField(max_length=255)),
                ('size_bytes', models.PositiveIntegerField()),
                ('page_count', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='course.course')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
